### ISSUE TITLE
悬浮翻译有时候我在我悬浮一个单词的时候能正常翻译，但是当悬浮`&&`的时候会把我整个文件的内容都触发翻译

### ISSUE THREAD

**Issue by huxianc** [wisenchen/wisen-translate#2]
比如我在`package.json`文件里面，随便hover一个单词，正常翻译了，这个时候移动鼠标，hover `&&`就会触发整个文件的翻译
![image](https://github.com/wisenchen/wisen-translate/assets/47603705/407e06da-b83c-4aab-8ea9-654b2eb0d3da)
将整个文件的翻译结果都打印出来了，当`package.json`中文字 length>5000的时候，`bing`是会报超出最大长度的

建议：

1. 将翻译结果不要打印出来，因为装了这个插件的也可能会开发插件，导致控制台可能会有大量打印信息，虽然可以通过设置暂时禁用hover translate
2. 将hover translate 上次结果缓存下来，不然当用户hover 频繁的时候，`bing`会返回`401`
3. 代码clone到本地，dev会报错
![image](https://github.com/wisenchen/wisen-translate/assets/47603705/b15a69f6-453f-46af-950f-3028525d7e78)

**Comment by wisenchen** [comment]
> 比如我在`package.json`文件里面，随便hover一个单词，正常翻译了，这个时候移动鼠标，hover `&&`就会触发整个文件的翻译 ![image](https://private-user-images.githubusercontent.com/47603705/346485168-407e06da-b83c-4aab-8ea9-654b2eb0d3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODYxMDAsIm5iZiI6MTcyMDU4NTgwMCwicGF0aCI6Ii80NzYwMzcwNS8zNDY0ODUxNjgtNDA3ZTA2ZGEtYjgzYy00YWFiLThlYTktNjU0YjJlYjBkM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA0MzAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MjMxMTI5MmZhMzdjYzFkYTcwMmMzY2ZmYjY4N2RlMzE4YTE5MWIzMzNhY2UwZTc1ODk3MGRkMjdlNjkyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0kSkpqEOd2Mk-cwjnrDLCHM3_kKtKMU8cbnyln46uxY) 将整个文件的翻译结果都打印出来了，当`package.json`中文字 length>5000的时候，`bing`是会报超出最大长度的
> 
> 建议：
> 
> 1. 将翻译结果不要打印出来，因为装了这个插件的也可能会开发插件，导致控制台可能会有大量打印信息，虽然可以通过设置暂时禁用hover translate
> 2. 将hover translate 上次结果缓存下来，不然当用户hover 频繁的时候，`bing`会返回`401`
> 3. 代码clone到本地，dev会报错
>    ![image](https://private-user-images.githubusercontent.com/47603705/346486857-b15a69f6-453f-46af-950f-3028525d7e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODYxMDAsIm5iZiI6MTcyMDU4NTgwMCwicGF0aCI6Ii80NzYwMzcwNS8zNDY0ODY4NTctYjE1YTY5ZjYtNDUzZi00NmFmLTk1MGYtMzAyODUyNWQ3ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA0MzAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNWU1YjFlNzZiYTZhNzVmMzYwYTQ4MDkxNjExMDkxZmM0ZjZiYTUzYzU0N2I0MTAzZjc1ZjczZWIzNWY1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nS-hsSm8YrIxiyaxH4I0ZLWxkpIDaNAWAByrtazNnyA)

您好，感谢您的反馈，1，3 目前已经处理了，2 缓存后续会考虑做的

**Comment by huxianc** [comment]
我看commit 里面我反馈的问题好像没有修复 只是将建议里面的1和3处理了

**Comment by wisenchen** [comment]
> 我看commit 里面我反馈的问题好像没有修复 只是将建议里面的1和3处理了

我这边没有复现，可以提供一下详细步骤吗？ 方便的话录个屏之类的看看，因为 hover 的文字是用的 VSCode 内置提供的 API，正常来讲除非 VSCode 提供的有问题

**Comment by huxianc** [comment]
![image](https://github.com/wisenchen/wisen-translate/assets/47603705/4ba06fd8-9912-4682-9d86-98f40af39dae)
F5 运行后，打开一个package.json 文件，hover一个&& 就会进入断点
![image](https://github.com/wisenchen/wisen-translate/assets/47603705/79e8e887-8068-4448-870f-2936e68fbfa2)

`let text = document.getText(document.getWordRangeAtPosition(position)).trim();` 直接返回了整个文本，因为没有选中字符，直接传到`translate`函数里面去了

**Comment by huxianc** [comment]
录屏：
https://github.com/wisenchen/wisen-translate/assets/47603705/f2594400-725d-4bd7-a808-54ee069f500d

**Comment by huxianc** [comment]
好像是 `document.getWordRangeAtPosition(position)` 返回的是`undefined`，然后`document.getText(undefined)`就获取的是所有文本，看是不是需要做一个 `document.getWordRangeAtPosition(position)` 为`undefined`的判断

**Comment by wisenchen** [comment]
感谢，我尝试下

**Comment by wisenchen** [comment]
> 好像是 `document.getWordRangeAtPosition(position)` 返回的是`undefined`，然后`document.getText(undefined)`就获取的是所有文本，看是不是需要做一个 `document.getWordRangeAtPosition(position)` 为`undefined`的判断

确实是这个问题，已修复
